name: ci-test

on:
  pull_request:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/etlegacy:${{ github.event.pull_request.head.sha }}

      - name: Synchronize Github description and README.md with Docker Hub
        uses: bemble/sync-readme@v1.0.0
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKER_PASS }}
          slug: ${{ secrets.DOCKERHUB_USERNAME }}/etlegacy
          readme: README.md
          description: true
