name: ci-test

on:
  pull_request:

env:
  TEST_TAG: sebdanielsson/etlegacy:${{ github.event.pull_request.head.sha }}

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Test Docker image  
        run: |
          # Download the pak files
          curl -O --output-dir ./data/etmain "https://mirror.etlegacy.com/etmain/pak[0-2].pk3"

          # Make the data directory writable
          chmod -R 777 ./data

          # Start the container in detached mode
          CONTAINER_ID=$(docker run -d --rm -p 27960:27960/udp -v "${PWD}/data/etmain:/etlegacy/etmain" ${{ env.TEST_TAG }})

          # Wait for 'heartbeat' or timeout
          TIMEOUT=300  # 5 minutes in seconds
          CHECK_INTERVAL=10  # Check every 10 seconds
          ELAPSED_TIME=0

          while [ $ELAPSED_TIME -lt $TIMEOUT ]; do
            if docker logs $CONTAINER_ID 2>&1 | grep -q "snusbeat"; then
              echo "Heartbeat message received."
              exit 0
            fi
            sleep $CHECK_INTERVAL
            ELAPSED_TIME=$((ELAPSED_TIME + CHECK_INTERVAL))
          done

          echo "Heartbeat message not received within $TIMEOUT seconds."
          exit 1

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.TEST_TAG }}

      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.TEST_TAG }}
